### ISSUE TITLE
event when ViewMode changed

### ISSUE THREAD

**Issue by julienGrd** [nheath99/NodaTimePicker#58]
Hi and thanks for your work !
I use your component for one of my project, and i need to handle some events
- when the view Mode change (`EventCallback<ViewMode> OnViewModeChanged`)
- when the month (view mode day) or the year (view mode month) change (`EventCallback<(int, int)> OnMonthChanged, argument year, month, and EventCallback<int> OnYearChanged, argument year`)

You think its possible to add this ?

if needed, i can develop on your repository to add this.

thanks !

Julien

**Comment by nheath99** [comment]
These events already exist, in a way, however they were initally implemented before EventCallback<T> was created, so they are generally just Action/Action<T>. The correct way to implement these events is of course EventCallback<T>, however there is some work to change this as it is a breaking change.

I can accept the first point, firing an event for OnViewModeChanged.
The second point seems redundant, as you will be notified of the OnViewModeChanged, and you will be able to interogate the current state at that point.

Thanks for your interest in this Julien!
Nick
