### ISSUE TITLE
add some span with class on text node

### ISSUE THREAD

**Issue by julienGrd** [nheath99/NodaTimePicker#59]
hi, i use your component for one of my project and it is amazing ! thanks !

I need to customize it to integrate it properly on my app, and it could be nice to have the node text surrunding by span to customize it better

before 
````
<div class="day-wrapper">
<button type="button" role="button" class="day weekday old disabled" style="">
    30
</button>
</div>
````

after
````
<div class="day-wrapper">
<button type="button" role="button" class="day weekday old disabled" style="">
<span class="text-day">
    30
</span>
</button>
</div>
````

same things for month, years, etc

I can do it if you want !

thanks !

Julien

**Comment by nheath99** [comment]
Hi Julien,

Thanks for the feedback. I have implemented this on the dev branch, using RenderFragments (https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#templated-components).

The default is just to show the Day number, however you could implement your requirements with the following code:

```
<DatePicker>
    <DayTemplate Context="day">
        <span class="text-day">@day.Day</span>
    </DayTemplate>
</DatePicker>
```
