### ISSUE TITLE
Formating input field date format

### ISSUE THREAD

**Issue by dinonovak** [nheath99/NodaTimePicker#60]
Hi all,

currently in Input box I am getting a long time format string: "Wednesday, 03 July 2019"
is there a way to convert this to "03.07.2019" format somehow?

**Comment by nheath99** [comment]
Yes this is possible. 
"Wednesday, 03 July 2019" is the default ToString display of LocalDate. In your input box, simply bind the value to something else:

````
<input type="text" value=@selectedDate?.ToString("dd.MM.yyyy", null) />
````
