### ISSUE TITLE
package is not recognized by nuget

### ISSUE THREAD

**Issue by hadiriazi** [nheath99/NodaTimePicker#63]
Trying to use this in my project but nuget wont find version 0.2.0

**Comment by nheath99** [comment]
There is an issue with the build at the moment, just waiting for Azure to allow access to the .Net Core 3.0.0 preview 7 SDK and it will be back up-and-running!

**Comment by julienGrd** [comment]
Hello, same thing with 0.3.0. It seem Nugget is still blocked on 0.1.0

**Comment by nheath99** [comment]
Apologies for the delay, version 0.3.0 up on NuGet now
