### ISSUE TITLE
.net standard 2.1 compatibility

### ISSUE THREAD

**Issue by julienGrd** [nheath99/NodaTimePicker#65]
Hi, i try to reference your library on my blazor app wich is on .net standard 2.1. The compilation work, but when i try to access the component on a view i have a JS error, he don't find your dll. When i put my client project on .net standard 2.0 everything work. I precise i reference directly your dll because your nugget is still blocked in a old version (0.1.0). 

Thanks !

**Comment by nheath99** [comment]
Hi, I've pushed version 0.3.0 to NuGet now, so please try again and let me know if there are any problems.
