### ISSUE TITLE
OnCleared never gets fired

### ISSUE THREAD

**Issue by arivera12** [nheath99/NodaTimePicker#79]
I think we are missing this thing on blue on the screenshot
![image](https://user-images.githubusercontent.com/5600102/65403084-590c6080-dda0-11e9-803d-12587c90f6a2.png)
I added that line and started working properly.

**Comment by arivera12** [comment]
is this gonna get fixed as well?

**Comment by nheath99** [comment]
Hi @arivera12 both this and #78 have been fixed. Please feel free to create a Pull Request if you have any quick fixes of your own, I want this to be a community project! Thanks again for your interest.

**Comment by arivera12** [comment]
I will fork it next time when ever I found another issue and PR to you. 

I still posted the code for you so its ain't so bad at all hehe.
